language: ruby
rvm:
  - 2.7
  - 3.0
  - 3.1
  - ruby-head
gemfile:
  - gemfiles/sidekiq_5.x.gemfile
  - gemfiles/sidekiq_6.1.gemfile
  - gemfiles/sidekiq_6.x.gemfile
  - gemfiles/sidekiq_7.x.gemfile
before_install:
  - gem update --system
  - gem update bundler
services: redis
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
